language: python
sudo: required
env:
- TOXENV=py27
- TOXENV=py34
install:
- "(!(test -f docker_packages.txt) || (cat docker_packages.txt | xargs sudo apt-get
  install -y))"
- pip install -r requirements_dev.txt
- pip install -r requirements.txt
script: npm run dist
notifications:
  slack:
    secure: l1r69U+5MPBuWJhISzQKI/ZeSWEA+kaOt3k/e+7VWe6m5x99asPzquqdA6IrNsRH1lYFaQ5gz2qt12GAQy4gXc0S3SSCLAVqCN6hdFJfAkAbY/mN6iyeIUsDdFRmg2lQANL6XZDVq8Lm6bUAiaWi05XEJn8pF/5esuF0E2HY+vkkIotIacYCKbJh5WKo+ZJjwa936+u0Q/ATFnuVWqvcfYhCMwTpJ6o/SQ40kR7QbuUclLQ9hz4IL2+MRldvwoKk87hOF0pz6ouLdOtIBsnLn2NjYsaxye9tiE6rWLDxXLf7edggmhKZ8UBfSLcWJx3QfYbctVhpif2SB4KqHnhmfXfbQbPIsPEQj0BrjjdUkWcjmWbfcu4NzYchjm+030SJL8UGzZQJ9k4MJnojCo0FIpKPrUkGYZ9CNOKNG0OHUsED40pwQkOXWndXsphRlilj383ydU6Hw9vZa6JbGpTNqCGzSzlXfOYCNey6Idogwo+7qxL+hsq+y9y174DbTxWFlL8eft5fZX32uvYeR+a7yBVmRRXyBrUIKG0yPHgL1QKlp/KnoJc+j76y1bEbz3yBIAIFy7xFZ3Gn3STzAt7wCE0f/ucwujNVaxqCLi4gcUiMnxf14B0+SKSSX/aX4clcBA/VXNqrsHUH+ZrvIyh7bXxVpLVIGqL0PufRcOuHztY=
    on_success: change
    on_failure: always
deploy:
- provider: releases
  api_key:
    secure: WbelUx3RnWAGV2CPzZKfTFoU00pFgVzvJeRR0Emco9BFdvKC6ox4bNpSvD8MrfnJlblc8NbXD9Ic/C+9aE4YG8PDKXcap/LeFivFr6msVh6WRi5oKNTxHGB9GpgplzwxVZDggTJCXnEV0EafNJjJKspfoLQJQJqKl5MJZefUQgXF1Kj2MadqVYwYZldbWVojxfpbcGzrOu3jBWpRE376Mqx/K3R5ImNG6WhaTbhuTWjQZWPowvd2ENZRGe4/qiNyGeUED682+Vekz3ZiUZ2IGlxJxzBiLLoN0UALf1/aCrPnG8c/Xa91mcxW10Tv67NgGsIB0NtTI7mrSVBDMMfSsFjwIfkR5QX7FlzGCUn/iuh5Ap8lY/gbaEGIF9areyB4WfytWPDsmYqiXsaonG+XpoYG2z/5hZ3q/PS+fMCGz+EqmDQ/MFfGPmPT2bx869tyKb4EkW+b+VSWb7QN87YnbxqiXS84taO7aHMbDxYq4wQoQ7+way8lOBS+UP7KCCWS6TJzZXRyXPdEldxQacnm/rG94U+vrBKJXYpjfUB9Lkrvgf5ZQr1oow4um7jhvNqdyMJcWTGEjVpgpmiMLaYcvLlrrYvW6IicVwWdEllRts1B/7USk3s0ifh1VkCpBDBlfpJ8tx18rGr2we+D9itjm2Em55JggxWLC8sJCs4YXbk=
  file_glob: true
  file: dist/phovea_data_redis*.egg
  on:
    tags: true
    repo: phovea/phovea_data_redis
- provider: pypi
  user: caleydo-bot
  password:
    secure: EE98+HAsE+YDta9ADVPVgFBNHqyOnzo3qyADCJDJopnJ9NyY4f8F1CGXZTxhzAiYo9yqLbEWqUXuVFA9WAslNlE+9r46ygzANcASPRTnOrvDr+v8pImTKroHi3hq76jZqqIvXfLHlnPJiYXnFZVXa4DpBSfwAM+tFHhRixzN4oqfqSx3xdAGoEFqlcBHMrkrezKZrgWp0rXJJ8QFLb3dNvdmupueRpoWHpQfJCF3gPjRBr0/crWseyzb5Ku80VfWxn0FtFcXxcyKxiFHfkz1YQccaP7/QlgEwjS8jGncPM6djIB/jZrJAleAhBPHkuoN/J7AF/DNvwOJsCpoISPpCx0so7SE7dnL1sXkApjI5eCTaMmb06qbA4joKRFFgD6b4IX+FZCE9koPD7OM0WwqRZAYW4jD3JzKjxrvBG2nmaoiU6jZe/B9pU3pmmc7PhfNXGwQcs9sZb7z/vhBEfHtnQSUxYeIxfwvzO4T5Oknj54C36EnkLFJIgo97+eiFS61iZ+McfhS/rUNMEuBkCIaAD13IleJvlFCZmh047Ak/+37KN8t39Du86Ds248l2DJs24xoP1R4OELcu6QlkDTRrgHfUwxYQvSH7g2sWcMpP1Nwu9FH0jiZyEsfBwVqteeKBfost7aDMOo2q6/2Q5lix65GHPFuwPYxPD+pLyiStQQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: phovea/phovea_data_redis
