version: '2.0'
services:
  _host:
    depends_on:
    - db_redis
    links:
    - db_redis:redis
  db_redis:
    image: redis:3.2-alpine
# run with appendonly to persist data
    command: 'redis-server --appendonly yes'
    volumes_from:
    - db_redis_data
  db_redis_data:
    image: redis:3.2-alpine